---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: update-bundle
spec:
  description: This tasks gets all the required data of an FBC build and commits it to a payload repository to be used in a GitOps environment.
  params:
    - name: snapshot
      type: string
  tasks:
    - name: update-bundle
      params:
        - name: SNAPSHOT
          value: "$(params.snapshot)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: snapshots-to-release
            description: Contents of the snapshots.json file
          - name: bundle-version
            description: NVR of the bundle
        volumes:
          - name: quay-creds
            secret:
              secretName: quay-builds-creds
        steps:
          - name: update-bundle
            image: quay.io/konflux-ci/release-service-utils@sha256:2f9e6863e82bbc9ddce5a290f3fd0e87657c475e3de8a832b2ef7f8d0671e7d3
            envFrom:
              - secretRef:
                  name: hco-updater-gitlab-token
            script: |
              #!/usr/bin/env bash
              set -eo pipefail

              SNAPSHOT_ID=$(echo "$(params.SNAPSHOT)" | awk -F'/' '{print $2}')
              SNAPSHOT_DATA=$(kubectl get snapshot $SNAPSHOT_ID -ojson)
              NAMESPACE=$(jq -r '.metadata.namespace' <<< "$SNAPSHOT_DATA")
              APPLICATION=$(jq -r '.spec.application' <<< "$SNAPSHOT_DATA")
              VERSION=$(echo "$NAMESPACE" | cut -d'-' -f1,2)
              REPO_URL="https://gitlab.cee.redhat.com/openshift-virtualization/konflux-builds/${VERSION}/hco-bundle-registry.git"
              REPO_URL=$(echo "$REPO_URL" | sed "s|https://|https://oauth2:${GITLAB_TOKEN}@|")

              git clone $REPO_URL --depth 50
              cd hco-bundle-registry
              git remote set-url origin "$REPO_URL"
              git config user.name "submodule-sync"
              git config user.email "no-reply@redhat.com"

              IMAGES=$(jq -r '.spec.components[].containerImage' <<< "$SNAPSHOT_DATA")

              # Make sure all the commits in every component are the same
              if jq -e '[.spec.components[].source.git.revision] | unique | length == 1' <<< "$SNAPSHOT_DATA" > /dev/null; then
                echo "The snapshot has all the components pointing to the same commit, continuing."
              else
                echo "Commits are inconsistent!"
                exit 1
              fi

              function update_images_snapshots() {
                for img in $IMAGES; do
                  image_name_sha=$(echo "${img##*/}")
                  image_name=$(echo "$image_name_sha" | cut -d'@' -f1)

                  if [[ "$image_name" == *"-operator-rhel"* ]]; then
                    json_file="components/hco-bundle-registry/core-params.json"
                  else
                    json_file="components/hco-bundle-registry/extra-params.json"
                  fi
                  jq ".\"${image_name}-image\" = \"${image_name_sha}\"" "$json_file" > "${json_file}.tmp" && mv "${json_file}.tmp" "$json_file"
                done

                snapshots_file="components/hco-bundle-registry/snapshots.json"
                touch ${snapshots_file}
                jq -n \
                  --slurpfile f "$snapshots_file" \
                  --arg app "$APPLICATION" \
                  --arg snap "$SNAPSHOT_ID" \
                  '$f[0] // {} | .[$app] = $snap' \
                > "$snapshots_file.tmp" \
                && mv "$snapshots_file.tmp" "$snapshots_file"
              }

              update_images_snapshots

              git add .
              # Check if there are actually changes before committing
              if ! git diff-index --quiet HEAD; then
                git commit -m "Update HCO bundle registry with new images"
                git pull --rebase origin main
                git push origin main
              else
                echo "No changes detected in the bundle registry. Skipping git push."
              fi

              if [[ "$(params.SNAPSHOT)" == *"hco-bundle-registry"* ]]; then
                REPO_REVISION=$(jq -r '.spec.components[].source.git.revision' <<< "$SNAPSHOT_DATA")

                BUNDLE_VERSION=$(cat build-bundle.json | jq -r '.metadata.Version | "\(.XY).\(.Z)-\(.release)" | sub("^v"; "")')
                echo -n "$BUNDLE_VERSION" > /tekton/results/bundle-version

                # Make sure we are getting the exact snapshots from the bundle
                git checkout $REPO_REVISION

                # Update the bundle snapshot as its not updated in this commit
                update_images_snapshots

                SNAPSHOTS_TO_RELEASE=$(cat $snapshots_file)
                echo -n "$SNAPSHOTS_TO_RELEASE" > /tekton/results/snapshots-to-release
              fi
          - name: push-release-chart
            image: quay.io/redhat-user-workloads/ocp-virt-images-tenant/pipeline-tools@sha256:18f9f819e9393891ce7ae19414a5672786e3efb120bdeaa2c254d8ba5d8e2493
            envFrom:
              - secretRef:
                  name: hco-updater-gitlab-token
              - secretRef:
                  name: quay-builds-creds
            volumeMounts:
              - name: quay-creds
                mountPath: /tmp/quay-builds-creds
                readOnly: true
            script: |
              #!/usr/bin/env bash
              set -eo pipefail

              # Only continue if its releasing hco-bundle-registry
              if [[ "$(params.SNAPSHOT)" != *"hco-bundle-registry"* ]]; then
                echo "Skipping push-release-chart: snapshot parameter does not contain 'hco-bundle-registry'"
                exit 0
              fi

              # Read results from previous step
              SNAPSHOTS_TO_RELEASE=$(cat /tekton/results/snapshots-to-release)
              BUNDLE_VERSION=$(cat /tekton/results/bundle-version)
              XY=$(echo "$BUNDLE_VERSION" | cut -d'.' -f1,2 | tr '.' '-')

              TMPDIR=$(mktemp -d)
              cd "$TMPDIR"
              export HOME=/tmp
              git clone https://gitlab.cee.redhat.com/openshift-virtualization/konflux-builds/release-chart.git --depth 1
              cd release-chart/release-orchestrator
              yq -i ".version = \"$BUNDLE_VERSION\"" Chart.yaml
              yq -i ".global.releasePlan = \"TODO-RELEASEPLAN\"" values.yaml
              yq -i ".global.targetNamespace = \"v${XY}-openshift-virtualization-tenant\"" values.yaml

              # Update values.yaml with snapshots from SNAPSHOTS_TO_RELEASE
              echo "$SNAPSHOTS_TO_RELEASE" | jq -r '{snapshots: .}' | yq eval -P '.' > /tmp/snapshots_with_key.yaml
              yq eval-all '. as $item ireduce ({}; . * $item)' values.yaml /tmp/snapshots_with_key.yaml -i

              DOCKER_CONFIG=$(cat /tmp/quay-builds-creds/.dockerconfigjson)
              QUAY_USERNAME=$(echo "${DOCKER_CONFIG}" | jq -r '.auths | to_entries[] | select(.key | contains("quay.io")) | .value.username')
              QUAY_PASSWORD=$(echo "${DOCKER_CONFIG}" | jq -r '.auths | to_entries[] | select(.key | contains("quay.io")) | .value.password')
              QUAY_URL=$(echo "${DOCKER_CONFIG}" | jq -r '.auths | to_entries[] | .key')

              echo "${QUAY_PASSWORD}" | helm registry login quay.io --username "${QUAY_USERNAME}" --password-stdin

              PACKAGE_OUTPUT=$(helm package . 2>&1)
              PACKAGE_FILE=$(echo "${PACKAGE_OUTPUT}" | grep -oP 'Successfully packaged chart and saved it to: \K.*')

              helm push $PACKAGE_FILE oci://${QUAY_URL}
