apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    pipelines.appstudio.openshift.io/type: build
  name: run-cnv-smoke-tests
spec:
  description: |
    TBD
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - description: Revision of the Source Repository
      default: ""
      name: revision
      type: string
    - description: Path to the source code of an application's component from where to build image.
      default: .
      name: path-context
      type: string
    - name: prow-job
      type: string
  tasks:
    - name: run-smoke-tests
      timeout: 4h0m0s
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
        - name: path-context
          value: $(params.path-context)
        - name: prow-job
          value: $(params.prow-job)
      taskSpec:
        params:
          - name: git-url
          - name: revision
          - name: path-context
          - name: prow-job
        results:
          - name: IMAGE_DIGEST
            description: Digest of the image just built
          - name: IMAGE_URL
            description: Image repository and tag where the built image was pushed
          - name: IMAGES
            description: List of all referenced image manifests
          - name: IMAGE_REF
            description: Image reference of the built image containing both the repository and the digest
          - name: SBOM_BLOB_URL
            description: Reference of SBOM blob digest to enable digest-based verification from provenance
            type: string
        volumes:
          - name: credentials
            emptyDir: {}
          - name: github-app-private-key
            secret:
              secretName: github-secrets
              items:
                - key: GITHUB_APP_PRIVATE_KEY
                  path: github_app_private_key.pem
        steps:
          - name: trigger-prow-job-via-gangway
            image: quay.io/cnv-qe-devops/gangway:latest
            env:
              - name: GIT_REVISION
                value: $(params.revision)
              - name: GIT_REPOSITORY
                value: $(params.git-url)
              - name: PATH_CONTEXT
                value: $(params.path-context)
              - name: PROW_JOB_NAME
                value: $(params.prow-job)
              - name: GANGWAY_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-secrets
                    key: GANGWAY_TOKEN
              - name: GIT_USER_NAME
                valueFrom:
                  secretKeyRef:
                    name: github-secrets
                    key: GIT_USER_NAME
              - name: GIT_USER_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: github-secrets
                    key: GIT_USER_EMAIL

              - name: GITHUB_APP_ID
                valueFrom:
                  secretKeyRef:
                    name: github-secrets
                    key: GITHUB_APP_ID
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-secrets
                    key: GITHUB_TOKEN
            volumeMounts:
              - name: credentials
                mountPath: /credentials
              - name: github-app-private-key
                mountPath: /credentials/github-app
                readOnly: true
            script: |
              #!/bin/bash

              set -xeuo pipefail

              git clone "${GIT_REPOSITORY}" repo && pushd "repo/${PATH_CONTEXT}" && git checkout "${GIT_REVISION}"

              export JOB_INFO_FILE="/tmp/prow.yaml"
              export CNV_OPERATOR_CHANNEL=$(yq '.channel' payload.yaml)
              export FREIGHT_NAME=$(yq '.freightName' payload.yaml)
              export HCO_BUNDLE_REGISTRY_BY_SHA=$(yq '.hco_bundle_registry_by_sha' payload.yaml)
              export HCO_BUNDLE_REGISTRY_BY_TAG=$(yq '.hco_bundle_registry_by_tag' payload.yaml)
              export HCO_BUNDLE_VERSION=$(yq '.hco_bundle_version' payload.yaml)
              export SNAPSHOT_ID=$(yq '.snapshot_id' payload.yaml)
              export CNV_CATALOG_IMAGE=$(yq '.index_image' payload.yaml)
              popd

              uv run gangway.py \
                  --trigger "${PROW_JOB_NAME}" \
                  --write-job-info-file ${JOB_INFO_FILE} \
                  -e CNV_CATALOG_IMAGE=${CNV_CATALOG_IMAGE} \
                  -e CNV_OPERATOR_CHANNEL=${CNV_OPERATOR_CHANNEL} \
                  -e HCO_BUNDLE_VERSION=${HCO_BUNDLE_VERSION}

              PROW_JOB_ID=$(yq '.prowJobId' ${JOB_INFO_FILE})

              uv run gangway.py \
              --write-job-info-file ${JOB_INFO_FILE} \
              --wait-job-id ${PROW_JOB_ID} || exit_code=$?

              export PROW_JOB_STATE=$(yq '.prowJobState' ${JOB_INFO_FILE})
              export PROW_JOB_URL=$(yq '.prowJobUrl' ${JOB_INFO_FILE})
              export PROW_JOB_YAML=$(yq '.prowJobYamlUrl' ${JOB_INFO_FILE})

              pushd "repo/${PATH_CONTEXT}"

              git fetch && git checkout main && git pull --ff


              yq --null-input \
                '
                .bundle        = env(HCO_BUNDLE_VERSION)   |
                .channel       = env(CNV_OPERATOR_CHANNEL) |
                .payloadCommit = env(GIT_REVISION)         |
                .prowJobUrl    = env(PROW_JOB_URL)         |
                .prowJobYaml   = env(PROW_JOB_YAML)        |
                .freightName   = env(FREIGHT_NAME)         |
                .smokeResults  = env(PROW_JOB_STATE)       |
                .snapshotID    = env(SNAPSHOT_ID)
                ' | yq 'sort_keys(..)' | tee smokeResults.yaml

              git config user.name "${GIT_USER_NAME}"
              git config user.email "${GIT_USER_EMAIL}"

              git add smokeResults.yaml
              git commit -m "🧪 Update Smoke Results For ${HCO_BUNDLE_VERSION}"

              curl -s https://gist.githubusercontent.com/rabin-io/01ab7e1d72ebd60932fd1a8e913b6245/raw/git-push.sh \
                | bash -s -- "${GITHUB_APP_ID}" "/credentials/github-app/github_app_private_key.pem"

  workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
